[package]
name = "easy_run"
version = "0.1.0"
authors = ["Tristan Wiesepape <wiesepapetristan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.19.0"
tabular = "0.1.4"
ctrlc = "3.1.7"
